blog/urls.py
from django.urls import path
from django.shortcuts import redirect

from . import views

urlpatterns = [
     
    path('', lambda _: redirect("blog-list")),
    path('list/', views.blog_list, name="blog-list"),
    path('<int:id>/<slug:title>/', views.blog_detail, name="blog-view"),
    
    path('<int:id>/<slug:title>/', views.blog_detail, name="blog-view"),
    
    path('terms-and-conditions/', views.t_and_c_view, name='t&c'),
    path('privacy/', views.privacy_view, name='privacy')

]

email_automation/urls.py
from django.contrib import admin
from django.conf import settings
from django.shortcuts import redirect
from django.conf.urls.static import static
from django.urls import path, include, re_path

from .views import (support_view, rate_limiter_view, view_404, 
                        handler_403, home_view)


admin.site.site_header = 'AtMailWIn'           
admin.site.index_title = 'Site Admin'              
admin.site.site_title = 'AtMailWin admin site'
admin.site.site_url = "https://atmailwin.com" 



handler404 = view_404

handler403 = handler_403



urlpatterns = [
    path('admin/', admin.site.urls),

    path('support/', support_view, name='support-view'),
    path('ratelimit-error/', rate_limiter_view, name='ratelimit-error'),

    path("", lambda r: redirect("home")),

    path('free-email-automation-tool/', home_view, name='home'),
    path('user/', include('user.urls')),
    path('blog/', include('blog.urls'), name="blogs"),
    
    path('email/', include('automail.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    
]
if settings.DEBUG:
   urlpatterns +=  []

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   
urlpatterns += [ re_path(r'^.*/$', view_404, name='page_not_found'),]

automail/models.py
from typing import Iterable, Optional
from django.db import models
from django.utils import timezone
from django.core.validators import RegexValidator

from encrypted_model_fields.fields import EncryptedCharField, EncryptedEmailField

from user.models import User

domain_name_validator = RegexValidator(regex='^[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9](?:\.[a-zA-Z]{2,})+$')

class EMAIL_SEND_RULES(models.IntegerChoices):

    """
        These rules determine how the follow up messages should be sent, eg: if ALL is set as
        rule the follow up will be sent to everyone to whom the first mail was sent.
    """

    ALL = (0, 'Respond for all')    
    NOT_RESPONDED = (1, 'Reply for not responded')
    RESPONDED = (2, 'Reply for responded')


class EmailConfiguration(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    name = models.CharField(max_length=40, null=True, blank=True)

    host = models.CharField(max_length=255)
    use_ssl = models.BooleanField(default=True)
    port = models.SmallIntegerField(default=465) # use ssl port

    imap_host = models.CharField(max_length=255, default='')

    email = EncryptedEmailField()
    password = EncryptedCharField(max_length=100)

    signature = models.TextField(null=True, blank=True, max_length=400)
    
    is_verified = models.BooleanField(default=False) # if the added email has been 

    def __str__(self) -> str:
        return f'{self.email}'

class EmailTemplate(models.Model):

    name = models.CharField(max_length=50, default="Sample Template")

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    subject = models.CharField(max_length=250, null=True, blank=True)

    body = models.TextField(max_length=10000)
    datetime = models.DateTimeField(auto_now=True)

    variables = models.TextField(max_length=2000, null=True, blank=True) # variables in the email structure, stored seperated by a comma

    public = models.BooleanField(default=False) # is this template public template

    copy_count = models.PositiveIntegerField(default=0) # this keeps a track of number copies of this template made

    def __str__(self) -> str:
        return f'{self.subject[:30]} #{self.pk}'
    

class EmailTemplateAttachment(models.Model):

    template = models.ForeignKey(EmailTemplate, on_delete=models.CASCADE)
    attachment = models.FileField(upload_to='attachments/')

    def __str__(self) -> str:
        return self.template.subject[:30]


class EmailCampaign(models.Model):

    name = models.CharField(max_length=30, default='campaign', null=True, blank=True)

    email_lookup = models.CharField(default='Email', max_length=150) # this is the field lookup upon uploading xls sheet
    created_datetime = models.DateTimeField(auto_now=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    file = models.FileField(upload_to='email-files/')
    save_to_inbox = models.BooleanField(default=True)
    discontinued = models.BooleanField(default=False) # if there are too many errors related to campaign discontinue the campaign

    def __str__(self) -> str:
        return f'{self.name}'
    

class EmailCampaignTemplate(models.Model):

    email = models.ForeignKey(EmailConfiguration, on_delete=models.CASCADE)
    campaign = models.ForeignKey(EmailCampaign, on_delete=models.CASCADE)
    template = models.ForeignKey(EmailTemplate, on_delete=models.CASCADE)

    followup =  models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    email_send_rule = models.PositiveSmallIntegerField(choices=EMAIL_SEND_RULES.choices, default=EMAIL_SEND_RULES.ALL, null=True)
    
    completed = models.BooleanField(default=False)

    created_datetime = models.DateTimeField(auto_now=True)
    sent_count = models.PositiveIntegerField(default=0)

    failed_count = models.PositiveIntegerField(default=0)
    failed_emails = models.TextField(max_length=4000, default='', null=True, blank=True) 
    error = models.TextField(max_length=4000, null=True, blank=True)
    smtp_error_count = models.PositiveIntegerField(default=0) 

    schedule = models.DateTimeField(null=True, blank=True)
    scheduled = models.BooleanField(default=False)
    
    created_datetime = models.DateTimeField(auto_now=True)


    def __str__(self) -> str:
        return f'{self.campaign.name}'

class BlacklistedEmailDomains(models.Model):

    """
        commonly known blacklisted email domains
    """

    domain = models.CharField(validators=[RegexValidator], max_length=255)

templates/html/email-product/campaign/campaign-details.html
{% extends './html/base.html' %}
{% load static %}
{% load tz %}
{% load custom_tags %}


{% block content %}
<div class="tw-flex tw-flex-col tw-min-h-[100vh] tw-p-3 tw-place-items-center tw-gap-4">

    <div class="modal model-dialog fade modal-dialog-centered !tw-hidden" id="delete-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Delete Campaign</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modal-body">
              Are you sure you want to delete this? This action cannot be undone
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form id="modal-btn-delete" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
          </div>
        </div>
    </div>

    <div class="tw-text-3xl tw-font-bold tw-m-5">
        {{campaign.name}}
    </div>


    <div class="tw-flex tw-flex-col tw-place-content-center tw-gap-4">
        <div class="tw-flex tw-w-full max-sm:tw-flex-col">
            <div class="tw-rounded-lg tw-shadow-lg tw-w-full tw-max-w-xl tw-flex tw-h-fit tw-overflow-hidden">
                <table class="table table-striped !tw-p-2 tw-mt-3 tw-min-w-[300px]">
                    <tr>
                        <td><b>Subject</b></td>
                        <td>{{ campaign.subject }}</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td><b>Template</b></td>
                        <td>{{ campaign.emailcampaigntemplate_set.first.template.name }}</td>
                        <td>
                            <button onclick="viewTemplate({{campaign.emailcampaigntemplate_set.first.template.id}})" class="btn !tw-max-w-fit" 
                                        data-bs-placement="bottom" title="View template"
                                        data-bs-toggle="modal" data-bs-target="#templateViewModel"
                                    >
                                    <i class="bi bi-eye-fill"></i>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td><b>Scheduled time</b></td>
                        <td>{% utc_to_local campaign.first_template_schedule request.COOKIES.user_timezone %}</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td><b>From</b></td>
                        <td>{{ campaign.emailcampaigntemplate_set.first.email.email }}</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td><b>Started</b></td>
                        <td>
                            {% if campaign.started %}
                                Yes
                            {% else %}
                                No
                            {% endif %}
                        </td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td><b>Completed</b></td>
                        <td> 
                            {% if campaign.emailcampaigntemplate_set.first.completed %}
                                Yes
                            {% else %}
                                No
                            {% endif %}
                        </td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td><b>File</b></td>
                        <td>{{ campaign.file|filename }}
                        </td>
                        <td>
                            <a href="{{ campaign.file.url }}" >
                                <i class="bi bi-download !tw-text-lg !tw-font-bold"></i>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td><b>Save to inbox</b></td>
                        <td>
                            {% if campaign.save_to_inbox %}
                                Yes
                            {% else %}
                                No
                            {% endif %}
                        </td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td><b>Sent count</b></td>
                        <td>{{ campaign.emailcampaigntemplate_set.first.sent_count }}</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td><b>Failed count</b></td>
                        <td>{{ campaign.emailcampaigntemplate_set.first.failed_count }}</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td><b>Failed emails</b></td>
                        <td>{{ campaign.emailcampaigntemplate_set.first.failed_emails }}</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td><b>Discontinued</b></td>
                        <td>
                            {% if campaign.discontinued %}
                                Yes
                            {% else %}
                                No
                            {% endif %}
                        </td>
                        <td>&nbsp;</td>
                    </tr>
                </table>
            </div>
            <div class="tw-flex tw-flex-col tw-gap-2 tw-max-w-lg max-sm:tw-mx-auto tw-mt-3 lg:tw-ml-auto tw-p-4">
                <button type="button" onclick="onDeleteCampaign('{% url 'email-campaign-delete' id=campaign.id %}', '{{ campaign.name }}')" 
                            class="btn btn-danger !tw-w-[200px]" data-bs-toggle="modal" data-bs-target="#delete-modal"><i class="bi bi-trash"></i>
                </button>
                <a href="{% url 'email-campaign-create' %}?edit={{ campaign.id }}" type="button" onclick="onDeleteCampaign('{% url 'email-campaign-delete' id=campaign.id %}', '{{ campaign.name }}')" 
                            class="btn btn-dark !tw-w-[200px] tw-flex" >
                        <span>Edit</span>
                        {% comment %} <i class="bi bi-pen"></i> {% endcomment %}
                </a>
            </div>
        </div>
        <hr>
        <div class="tw-text-center tw-text-xl tw-font-semibold">Follow ups</div>

        <div class="tw-w-full tw-flex tw-flex-wrap tw-place-content-center tw-gap-4">

            {% for x in campaign.emailcampaigntemplate_set.all %}
                {% if not forloop.first %}
                <div class="tw-rounded-lg tw-shadow-lg tw-flex 
                            tw-flex-col tw-h-fit tw-overflow-hidden
                            tw-max-w-[500px] tw-min-w-[300px]
                            ">
                    <div class="tw-text-center">{{forloop.counter|subtract:1}}</div>
                    <table class="table table-striped tw-mt-3 tw-min-w-[300px]">
                        <tr>
                            <td><b>Subject</b></td>
                            <td>{{ x.template.subject }}</td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td><b>Template</b></td>
                            <td>{{ x.template.name }}</td>
                            <td>
                                <a href="">
                                    <i class="bi bi-eye-fill"></i>
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td><b>Scheduled time</b></td>
                            <td>
                                
                                {% utc_to_local x.schedule request.COOKIES.user_timezone %}

                            </td>
                            <td>&nbsp;</td>
                        </tr>

                        <tr>
                            <td><b>Completed</b></td>
                            <td> 
                                {% if x.completed %}
                                    Yes
                                {% else %}
                                    No
                                {% endif %}
                            </td>
                            <td>&nbsp;</td>
                        </tr>
        
                        <tr>
                            <td><b>Sent count</b></td>
                            <td>{{ x.sent_count }}</td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td><b>Failed count</b></td>
                            <td>{{ x.failed_count }}</td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td><b>Failed emails</b></td>
                            <td>{{ x.failed_emails }}</td>
                            <td>&nbsp;</td>
                        </tr>
                    </table>
                </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>

</div>

<script src="{% static "./js/email-product/email-campaigns.js" %}"></script>

{% endblock content %}

templates/html/email-product/campaign/email-campaign-create.html
{% extends './html/base.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}
<div class="tw-flex tw-flex-col tw-min-h-[100vh] tw-p-3 tw-place-items-center tw-gap-4">
    <div class="tw-text-3xl tw-font-semibold tw-text-center tw-mt-[2%]">
        Create Email Campaign
    </div>
    
    <div class="alert alert-danger {% if not errors %}tw-hidden{% endif %}" id="template-alert">
        {% for x in errors %}
            {{x}}
        {% endfor %}
    </div>
            

    <form action="" method="post" enctype="multipart/form-data" onsubmit="return checkFields()" class="tw-flex tw-flex-col tw-p-3 tw-place-items-center tw-gap-4">
        {% csrf_token %}
        <div class="tw-min-h-[250px] tw-min-w-[200px] tw-shadow-lg tw-rounded-lg tw-mt-1 tw-p-4
                    tw-flex tw-flex-col tw-gap-2" id="campaign">

            <div class="input-group mb-3">
                <span class="input-group-text" id="">Campaign name</span>
                <input type="text" class="form-control" name="name" id="basic-url" autofocus 
                        value="{% if campaign.name %}{{campaign.name}}{% else %}Sample Campaign{% endif %}" 
                        placeholder="Campaign name" maxlength="30">
            </div>  
            <div class="tw-flex">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="">Default Email column</span>
                    <input type="text" class="form-control" name="email_lookup" id="basic-url" autofocus 
                            value="{% if campaign.email_lookup %}{{campaign.email_lookup}}{% else %}Email{% endif %}" 
                            placeholder="default email address column"
                            maxlength="30"
                            > 
                </div>        
                <i class="bi bi-info-circle-fill tw-m-1" data-bs-toggle="tooltip" data-bs-placement="bottom" 
                    title="The email column in the excel sheet"></i>
            </div>
            <div class="tw-flex tw-flex-col">
                <label for="addresses" class="form-label tw-font-medium">To Email address</label>
                <label class="btn btn-dark" id="addresses">
                    <input type="file" name="file" title="{{campaign.file}}"  accept=".xlsx, .xls, .csv"  class="tw-hidden" id="file-upload" />
                    <span>Upload excel file</span>  
                    <i class="bi bi-filetype-xls tw-text-xl" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Add excel file max 300kb"></i>
                </label>
            </div>
            <div id="selected-file-name" class="tw-text-sm">
                {% if campaign.file %}
                    {{campaign.file|filename}}
                {% else %}
                    No file selected
                {% endif %}
            </div>
        
            <div class="tw-mt-[2%] tw-font-medium">Select From address</div>
            <select class="form-select" value="{{campaign.emailcampaigntemplate_set.first.email.id}}" name="from_email">
                <option selected value="">From address</option>
                {% for e in emails %}
                    <option {% if campaign.emailcampaigntemplate_set.first.email.id == e.id %}selected{% endif %} value="{{e.id}}">{{e.email}}</option>
                {% endfor %}
            </select>
            <div class="tw-mt-[2%] tw-font-medium">Select email template</div>
            <div class="tw-flex tw-gap-1">
                <select class="form-select" name="template" value="{{campaign.emailcampaigntemplate_set.first.template.id}}" onchange="templatePreview()">
                    <option value="" selected>Choose Template</option>
                    {% for template in templates %}
                        <option {% if campaign.emailcampaigntemplate_set.first.template.id == template.id %}selected{% endif %} value="{{template.id}}">{{template.name}} #{{template.id}}</option>
                    {% endfor %}
                </select>
                {% comment %} <a  class="btn btn-light" id="template-view" url="{% url 'email-template-create' %}" target="_blank" rel="noreferrer">
                    <i class="bi bi-eye-fill"></i>
                </a> {% endcomment %}
                <button onclick="viewTemplate({{campaign.emailcampaigntemplate_set.first.template.id}})" id="template-view" type="button" class="btn !tw-max-w-fit" 
                                    data-bs-placement="bottom" title="View template"
                                    data-bs-toggle="modal" data-bs-target="#templateViewModel"
                                >
                        <i class="bi bi-eye-fill"></i>
                </button>
            </div>
            <div class="input-group mb-3 tw-mt-2">
                <span class="input-group-text" id="">Schedule (UTC time)</span>
                {% with campaign.emailcampaigntemplate_set.first.schedule as utc_time %}
                    {% utc_to_local utc_time request.COOKIES.user_timezone '%Y-%m-%dT%H:%M' as local_time %}
                    <input type="datetime-local" class="form-control" name="schedule" id="schedule_time" required 
                        value="{{ local_time }}" 
                        placeholder="default email address column" onchange="updateLocalTime()">
                {% endwith %}
            </div>  
            <div class="tw-text-sm" id="local-time">
            </div>

            <div class="form-check !tw-w-full tw-mt-2 tw-text-lg !tw-place-items-center !tw-flex">
                
                <input class="form-check-input !tw-ml-auto" onchange="" type="checkbox"
                    value="scheduled" 
                    name="scheduled" 
                    {% if campaign.emailcampaigntemplate_set.first.scheduled %} checked  {% endif %}4
                    {% if not campaign.emailcampaigntemplate_set.first %}checked{% endif %}
                    id="scheduled">
                <label class="form-check-label tw-m-1" for="scheduled">
                    Schedule
                </label>
            </div>

            <div class="form-check !tw-w-full tw-mt-2 tw-text-lg !tw-place-items-center !tw-flex !tw-hidden">
                <input class="form-check-input !tw-ml-auto" onchange="" 
                    type="checkbox" 
                    value="inbox" 
                    {% if campaign.save_to_inbox %} checked  {% endif %}4
                    {% if not campaign.exist %}checked{% endif %}
                    name="save_to_inbox" id="inbox-save">
                <label class="form-check-label tw-m-1" for="inbox-save">
                    Save to inbox
                    <i class="bi bi-info-circle-fill" data-bs-toggle="tooltip" data-bs-placement="bottom" title="sent mail won't appear in your inbox if this is not checked"></i>
                </label>
            </div>

        </div>

        <div class="tw-text-2xl tw-text-center tw-mt-[2%]">
            Follow up
        </div>

        <div class="tw-flex tw-flex-wrap tw-gap-2 tw-w-full tw-place-content-center" id="followup-section">
            
            {% for followup in campaign.emailcampaigntemplate_set.all|dictsort:"id"  %}
                {% if not forloop.first and followup.followup %}
                    <div class="tw-min-h-[150px] tw-min-w-[200px] tw-shadow-lg tw-rounded-lg tw-mt-[2%] tw-p-4
                        tw-flex tw-flex-col tw-gap-2" id="{{followup.id}}" title="follow-up">
                        <select class="form-select" value="{{followup.template.id}}" name="followup-template" onchange="viewTemplate({{template.id}})">
                            <option selected value="">Choose Template</option>
                            {% for template in templates %}
                                <option {% if followup.template.id == template.id %}selected{% endif %} value="{{template.id}}">
                                    {{template.name}} #{{template.id}}
                                </option>
                            {% endfor %}
                        </select>
                        <select class="form-select" name="rule">
                            <option selected value="">Select rule</option>
                            {% for rule in rules %}
                                <option {% if followup.email_send_rule == rule.0 %}selected{% endif %} value="{{rule.0}}">
                                    {{rule.1}}
                                </option>
                            {% endfor %}
                        </select>

                        <div class="input-group mb-3">
                            <span class="input-group-text" id="">Schedule</span>
                            {% with followup.schedule as utc_time %}
                                {% utc_to_local utc_time request.COOKIES.user_timezone "%Y-%m-%dT%H:%M" as schedule%}
                                <input type="datetime-local" class="form-control" name="followup-schedule" id="basic-url" autofocus 
                                    value="{{ schedule }}" 
                                    placeholder="Schedule">
                            {% endwith %}
                            {% comment %} <input type="datetime-local" class="form-control" name="followup-schedule" id="basic-url" autofocus 
                                        value="{{followup.schedule|date:'Y-m-d\TH:i'}}" 
                                        placeholder="Schedule"> {% endcomment %}
                        </div>  

                        <div class="form-check !tw-w-full tw-mt-2 tw-text-lg !tw-place-items-center !tw-flex">
                            <button class="btn" type="button" onclick="deleteFollowup('{{followup.id}}')">
                                <i class="tw-text-red-600 bi bi-trash"></i>
                            </button>
                            <input class="form-check-input !tw-ml-auto" type="checkbox" 
                                    value="followup-scheduled" name="followup-scheduled" 
                                    {% if followup.scheduled %} checked  {% endif %}
                                    id="scheduled-{{followup.id}}">
                            <label class="form-check-label tw-m-1" for="scheduled-{{followup.id}}">
                                Schedule
                            </label>
                        </div>

                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <!-- Hidden field for dynamic follow-up data -->
        <input type="hidden" name="followups" id="hidden-followups" value="[]">
    
        <button type="button" class="btn btn-warning" id="followup-btn">Add follow up</button>

        <button type="submit" class="btn btn-success !tw-w-[100px]">Save</button>
    </form>

    <hr >
 
    <div class="tw-flex tw-flex-col tw-place-items-center lg:tw-mx-[20%] tw-leading-8 tw-gap-2 tw-p-3">

        <div class="tw-font-medium tw-text-2xl">
            Usage guide
        </div>

        <div class="tw-text-md tw-text-base tw-leading-8 tw-mt-2 tw-text-justify">
            Creating templates campaigns are fairly straight forward. 
            However here are some points to note.

            <ul>
                <li>
                    The excel/csv file that you upload should contain email column, that contains recipient address.
                </li>
                <li>
                    
                    Make sure that you don't add too many recipients in the same excel file. Ideally limit to 
                    <b>less than 500 email recipients per day </b>. Other wise your mail may end up in spam and may get locked.
                   
                </li>
                <li>
                    Using the service to send unwanted spam can result in your email being locked by you email provider
                </li>
                <li>
                    <code>Default Email column</code> is the name column in your excel sheet that contains email addresses.
                </li>
                <li>
                    The rule in the follow up specifies if the mail should be sent to the
                    responded recipients.
                </li>
            </ul>
        </div>
            
    </div>

</div>
{{ templates|json_script:"templates" }}
{{ rules|json_script:"rules" }}
<script src="{% static "./js/email-product/campaign-create.js" %}"></script>
{% endblock content %}