blog/urls.py
from django.urls import path
from django.shortcuts import redirect

from . import views

urlpatterns = [
     
    path('', lambda _: redirect("blog-list")),
    path('list/', views.blog_list, name="blog-list"),
    path('<int:id>/<slug:title>/', views.blog_detail, name="blog-view"),
    
    path('<int:id>/<slug:title>/', views.blog_detail, name="blog-view"),
    
    path('terms-and-conditions/', views.t_and_c_view, name='t&c'),
    path('privacy/', views.privacy_view, name='privacy')

]

email_automation/urls.py
from django.contrib import admin
from django.conf import settings
from django.shortcuts import redirect
from django.conf.urls.static import static
from django.urls import path, include, re_path

from .views import (support_view, rate_limiter_view, view_404, 
                        handler_403, home_view)


admin.site.site_header = 'AtMailWIn'           
admin.site.index_title = 'Site Admin'              
admin.site.site_title = 'AtMailWin admin site'
admin.site.site_url = "https://atmailwin.com" 



handler404 = view_404

handler403 = handler_403



urlpatterns = [
    path('admin/', admin.site.urls),

    path('support/', support_view, name='support-view'),
    path('ratelimit-error/', rate_limiter_view, name='ratelimit-error'),

    path("", lambda r: redirect("home")),

    path('free-email-automation-tool/', home_view, name='home'),
    path('user/', include('user.urls')),
    path('blog/', include('blog.urls'), name="blogs"),
    
    path('email/', include('automail.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    
]
if settings.DEBUG:
   urlpatterns +=  []

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   
urlpatterns += [ re_path(r'^.*/$', view_404, name='page_not_found'),]

automail/models.py
from typing import Iterable, Optional
from django.db import models
from django.utils import timezone
from django.core.validators import RegexValidator

from encrypted_model_fields.fields import EncryptedCharField, EncryptedEmailField

from user.models import User

domain_name_validator = RegexValidator(regex='^[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9](?:\.[a-zA-Z]{2,})+$')

class EMAIL_SEND_RULES(models.IntegerChoices):

    """
        These rules determine how the follow up messages should be sent, eg: if ALL is set as
        rule the follow up will be sent to everyone to whom the first mail was sent.
    """

    ALL = (0, 'Respond for all')    
    NOT_RESPONDED = (1, 'Reply for not responded')
    RESPONDED = (2, 'Reply for responded')


class EmailConfiguration(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    name = models.CharField(max_length=40, null=True, blank=True)

    host = models.CharField(max_length=255)
    use_ssl = models.BooleanField(default=True)
    port = models.SmallIntegerField(default=465) # use ssl port

    imap_host = models.CharField(max_length=255, default='')

    email = EncryptedEmailField()
    password = EncryptedCharField(max_length=100)

    signature = models.TextField(null=True, blank=True, max_length=400)
    
    is_verified = models.BooleanField(default=False) # if the added email has been 

    def __str__(self) -> str:
        return f'{self.email}'

class EmailTemplate(models.Model):

    name = models.CharField(max_length=50, default="Sample Template")

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    subject = models.CharField(max_length=250, null=True, blank=True)

    body = models.TextField(max_length=10000)
    datetime = models.DateTimeField(auto_now=True)

    variables = models.TextField(max_length=2000, null=True, blank=True) # variables in the email structure, stored seperated by a comma

    public = models.BooleanField(default=False) # is this template public template

    copy_count = models.PositiveIntegerField(default=0) # this keeps a track of number copies of this template made

    def __str__(self) -> str:
        return f'{self.subject[:30]} #{self.pk}'
    

class EmailTemplateAttachment(models.Model):

    template = models.ForeignKey(EmailTemplate, on_delete=models.CASCADE)
    attachment = models.FileField(upload_to='attachments/')

    def __str__(self) -> str:
        return self.template.subject[:30]


class EmailCampaign(models.Model):

    name = models.CharField(max_length=30, default='campaign', null=True, blank=True)

    email_lookup = models.CharField(default='Email', max_length=150) # this is the field lookup upon uploading xls sheet
    created_datetime = models.DateTimeField(auto_now=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    file = models.FileField(upload_to='email-files/')
    save_to_inbox = models.BooleanField(default=True)
    discontinued = models.BooleanField(default=False) # if there are too many errors related to campaign discontinue the campaign

    def __str__(self) -> str:
        return f'{self.name}'
    

class EmailCampaignTemplate(models.Model):

    email = models.ForeignKey(EmailConfiguration, on_delete=models.CASCADE)
    campaign = models.ForeignKey(EmailCampaign, on_delete=models.CASCADE)
    template = models.ForeignKey(EmailTemplate, on_delete=models.CASCADE)

    followup =  models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    email_send_rule = models.PositiveSmallIntegerField(choices=EMAIL_SEND_RULES.choices, default=EMAIL_SEND_RULES.ALL, null=True)
    
    completed = models.BooleanField(default=False)

    created_datetime = models.DateTimeField(auto_now=True)
    sent_count = models.PositiveIntegerField(default=0)

    failed_count = models.PositiveIntegerField(default=0)
    failed_emails = models.TextField(max_length=4000, default='', null=True, blank=True) 
    error = models.TextField(max_length=4000, null=True, blank=True)
    smtp_error_count = models.PositiveIntegerField(default=0) 

    schedule = models.DateTimeField(null=True, blank=True)
    scheduled = models.BooleanField(default=False)
    
    created_datetime = models.DateTimeField(auto_now=True)


    def __str__(self) -> str:
        return f'{self.campaign.name}'

class BlacklistedEmailDomains(models.Model):

    """
        commonly known blacklisted email domains
    """

    domain = models.CharField(validators=[RegexValidator], max_length=255)

templates/html/email-product/templates/email-template-create.html
{% extends './html/base.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}

    <div class="tw-flex tw-flex-col tw--min-h-[100vh] tw-p-3 tw-place-items-center tw-gap-4">
        <div class="tw-max-w-[800px] tw-flex tw-flex-col">
            <div class="tw-text-3xl tw-font-semibold tw-text-center tw-mt-[5%]">
                Create email template
            </div>

            <div id="error-toast" class="toast tw-h-max tw-z-[5000] tw-fixed tw-top-[2%] tw-left-[50%] tw-translate-x-[-50%] align-items-center text-bg-danger border-0" 
                role="alert" aria-live="assertive" aria-atomic="true">
                <div class="d-flex">
                    <div class="toast-body" id="error-toast-body">
                    
                    </div>
                    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
            </div>
           
            <form action="{% url "email-template-create" %}{% if edit %}?edit={{edit}}{% endif %}" id="template-create" enctype="multipart/form-data" onsubmit="return validateTemplate()"
                    method="POST" class="tw-flex tw-flex-col tw-gap-3 tw-mt-[5%]">
                {% csrf_token %}

                <div class="alert alert-danger tw-hidden" id="template-alert">
                    {% for x in errors %}
                        {{x}}
                    {% endfor %}
                </div>

                
                <input type="text" class="tw-appearance-none tw-bg-transparent tw-border-solid
                                            tw-border-b-2 tw-border-0 tw-w-full tw-text-gray-700 tw-leading-tight 
                                            focus:tw-border-0 focus:tw-border-b-2
                                            tw-mb-[2%]
                                            "
                         name="name" value="{% if template.name %}{{template.name}}{% else %}Sample Template{% endif %}" placeholder="Template name" required maxlength="35">


                <div class="tw-flex tw-flex-col tw-gap-3 tw-z-[1]">
                    <input type="text" class="form-control" name="subject" 
                            placeholder="subject" value="{{template.subject}}" required maxlength="200" autofocus>
                    
                    <div class="editor-container tw-relative">
                        <input id="content" value="{{template.body}}" placeholder="write your draft" 
                                type="hidden" name="body" required>
                    
                        <trix-editor input="content" required id="trix-editor" class="form-control tw-max-h-[450px] tw-overflow-auto [&>a]:tw-text-blue-700" 
                                                        placeholder="Enter the mail body"></trix-editor>
                        <div id="autoCompleteDropDown"></div>
                    </div>

                    <div id="file-previewContainer" class="tw-flex tw-flex-wrap tw-gap-2 tw-grid-cols-2">
                        {% for attachment in template.emailtemplateattachment_set.all %}
                            <div class="tw-shadow-lg tw-p-1 !tw-w-fit tw-border-solid
                                        tw-border-[0.2px] tw-border-gray-700 tw-max-w-[150px] 
                                        tw-flex tw-gap-2 tw-place-items-center"
                                        id="attachment-{{attachment.id}}"
                                        >
                                <input type="hidden" name="existing-attachments" value="{{attachment.id}}">
                                <span>{{ attachment.attachment|filename }}</span>
                                <a href="{{ attachment.attachment.url }}" 
                                        class="tw-text-xl tw-font-semibold bi bi-download"
                                     target="_blank">
                                </a>
                                <button type="button" class="btn btn-close" onclick="removeFileAttachment('attachment-{{attachment.id}}')">

                                </button>
                            </div>
                        {% endfor %}
                    </div>

                    <div class="tw-flex tw-mt-[2%] tw-place-content-end ">
                        <label class="btn btn-warning tw-ml-auto ">
                            <input type="file" name="attachment" multiple class="tw-hidden" id="file-upload" />
                            <span>Attach file</span>  
                            <i class="bi bi-paperclip" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Add attachments max 10MB"></i>
                        </label>
                    </div>

                    <div class="form-check tw-ml-auto tw-mt-[5%]">
                        <input class="form-check-input" type="checkbox" onclick="warnUserOnPublic()" name="public" value="public" {% if template.public %}checked{% endif %} id="flexCheckDefault">
                        <label class="form-check-label" for="flexCheckDefault">
                            Public template
                        </label>
                        <i class="bi bi-info-circle-fill" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Make this template public for anyone on the internet"></i>
                    </div>

                    <div class="tw-flex tw-mt-[2%] tw-gap-2">
                        <button onclick="templateRenderPreview()" type="button" class="btn btn-dark !tw-max-w-fit" 
                        data-bs-placement="bottom" title="View template"
                        data-bs-toggle="modal" data-bs-target="#templateViewModel"
                        >
                            <span>Rendered Preview</span>
                        </button>
                        <button type="button" id="test-mail-btn" class="btn btn-primary">Send Test mail</button>
                        <button type="submit" class="btn btn-success tw-ml-auto">Save Template</button>
                    </div>
                </div>
                <div class="width-1700:tw-absolute width-1700:tw-top-[20%] width-1700:tw-max-w-[350px] width-1700:tw-right-[5%] tw-z-[0] tw-mt-[4%] tw-flex-col tw-flex tw-gap-2">
                    <div class="tw-text-sm">
                        Add fields structured in the following format {name: "sample name", age: "30"}
                    </div>
                    <textarea name="variables" class="form-control !tw-max-h-[250px]" placeholder="Add email variables" 
                                id="variables" oninput="validateVariables()" value="{{template.variables}}" cols="30" rows="10">{{template.variables}}</textarea>
                    
                    <div class="tw-flex tw-mt-[2%] tw-place-content-end ">
                        <label class="btn btn-warning tw-ml-auto ">
                            <input type="file" class="tw-hidden" accept=".xlsx, .xls, .csv" id="variables-upload" />
                            <span>Upload Excel file</span>  
                            <i class="bi bi-upload" data-bs-toggle="tooltip" data-bs-placement="bottom" title="upload variables"></i>
                        </label>
                    </div>
                    
                </div>
            </form>
            <hr class="tw-mt-[5%]">

            <div class="tw-flex tw-flex-col tw-place-items-center tw-leading-8 tw-gap-2 tw-p-3">

                <div class="tw-font-medium tw-text-2xl">
                    Usage guide
                </div>

                {% verbatim %}
                    <div class="tw-text-md tw-mt-2 tw-text-justify">
                        Creating templates is quite simple. Once you create a template,
                        you can use the same in many different Email campaigns. 

                        Here are some of the things that will help you working with templates.

                        <ul>
                            <li>
                                Template body and subjects can have variables represented by <code>{{variable_name}}</code>.
                                These variables will be replaced by actual values when you upoad the excel file during the campaign creation.
                            </li>
                            <li>Templates can have if else statements <code>{% if condition %} statement {% endif %}</code>. </li>
                            <li>
                                Templates have predefiend variables such as <code>{{from_name}}</code>, 
                                <code>{{from_email}}</code>, <code>{{from_signature}}</code>. These variables will be 
                                replaced by the values you provided in the email configuration.
                            </li>
                        </ul>
                    </div>
                    <div class="tw-font-medium tw-text-xl">
                        Sample usage
                    </div>

                    <div class="tw-mt-3 tw-text-md">
                        Hello {{name}},<br>
                        Hope you are doing well. I am {{from_name}} reaching out to you to 
                        inquire about your experience using this automation platform. It looks like your experience with us is 
                        {% if feedback == "positive" %} positive {% else %} negative {% endif %}. We would be grateful,
                        if you could explain a little more about your feed back.
                        <br>
                        <br>
                        {{from_signature}}
                    </div>
                {% endverbatim %}
            </div>

        </div>
    </div>

    <style>
        trix-toolbar .trix-button {
            background: #fff !important;
          }
    </style>

    <link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.0/dist/trix.css">
    <script type="text/javascript" src="https://unpkg.com/trix@2.0.0/dist/trix.umd.min.js"></script>

    <script src="{% static "./js/utils/trix-autocomplete.js" %}"></script>
    <script src="{% static "./js/email-product/email-template-create.js" %}"></script>

{% endblock content %}

templates/html/email-product/templates/email-templates.html
{% extends './html/base.html' %}
{% load static %}

{% block content %}
<div class="tw-flex tw-flex-col tw-min-h-[100vh] tw-p-3 tw-place-items-center tw-gap-4">

    <div class="modal model-dialog fade modal-dialog-centered !tw-hidden" id="delete-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Delete Template</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modal-body">
              Are you sure you want to delete this? This action cannot be undone
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form action="" id="modal-btn-delete" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
          </div>
        </div>
    </div>

    <div class="tw-text-3xl tw-font-semibold tw-text-center tw-mt-[2%]">
       My Email Templates
    </div>

    <div class="tw-flex tw-flex-wrap tw-place-content-center tw-mt-[2%] tw-w-full tw-gap-4 tw-mx-[30%]">

        <a class="tw-flex tw-flex-col tw-border-solid 
                    tw-text-center tw-justify-items-center 
                    tw-place-content-center 
                    tw-w-[250px] tw-g-[150px] 
                    tw-rounded-lg tw-shadow-xl tw-p-5"
                    href="{% url "email-template-create" %}"
                    >
            <i class="bi bi-plus-lg tw-text-3xl"></i>
            <p>Create template</p>
        </a>  

        {% for template in private_templates %}
            <div class="tw-flex tw-flex-col tw-border-solid 
                        tw-justify-items-center 
                        tw-border-gray-700
                        tw-border
                        tw-w-[250px] tw-h-[250px] 
                        tw-rounded-lg tw-shadow-xl tw-p-5"
                        >
                <span class="tw-text-center tw-font-semibold tw-text-sm">{{template.name}} #{{template.id}}</span>
                <div class="tw-mt-2"><b>Subject:</b> {{template.subject}}</div>
                <div class="tw-flex tw-gap-1 tw-mt-auto tw-text-2xl">
                    <button onclick="viewTemplate({{template.id}})" class="btn !tw-max-w-fit" 
                        data-bs-placement="bottom" title="View template"
                        data-bs-toggle="modal" data-bs-target="#templateViewModel"
                    >
                        <i class="bi bi-eye-fill"></i>
                    </button>
                    <button type="submit" onclick="onDeleteTemplate('{% url 'email-template-delete' id=template.id %}', `{{ template.name }} #{{ template.id }}`)" 
                            class="btn !tw-text-red-600 tw-w-full" data-bs-toggle="modal" data-bs-target="#delete-modal"><i class="bi bi-trash"></i>
                    </button>
                    <a class="btn !tw-border-solid !tw-border" href="{% url 'email-template-create' %}?copy={{ template.id }}" 
                        data-bs-toggle="tooltip" data-bs-placement="bottom" title="Duplicate">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-copy" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M4 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V2Zm2-1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H6ZM2 5a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-1h1v1a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h1v1H2Z"></path>
                        </svg>
                    </a>
                    <a class="btn !tw-border-solid tw-w-full" href="{% url 'email-template-create' %}?edit={{ template.id }}"
                        data-bs-toggle="tooltip" data-bs-placement="bottom" title="Edit"
                        >
                        <i class="bi bi-pencil-fill"></i>
                    </a>
                </div>                
            </div>
        {% endfor %}
    </div>  
    <hr>
    <div class="tw-text-2xl">
        Public Email templates
    </div>
    <div class="tw-flex tw-mt-[2%] tw-w-full tw-place-content-center tw-flex-wrap tw-gap-4 tw-mx-[30%]">
        {% for template in public_templates %}
            <div class="tw-flex tw-flex-col tw-border-solid 
                        tw-border
                        tw-text-left 
                        tw-justify-items-center 
                        tw-place-items-center 
                        tw-w-[250px] tw-h-[250px] 
                        tw-rounded-lg tw-shadow-xl tw-p-3
                        tw-overflow-hidden
                        "
                        >
                <b>{{template.name}}</b>
                <p class="tw-h-[80px] tw-overflow-auto tw-mt-2"> <b>Subject:</b>  {{template.subject}}</p>
                <p>by: {{template.user.name}}</p>
                <div class="tw-flex tw-gap-1 tw-mt-auto tw-w-[80%] tw-text-center">
                    <button onclick="viewTemplate({{template.id}})" class="btn !tw-max-w-fit" 
                        data-bs-placement="bottom" title="View template"
                        data-bs-toggle="modal" data-bs-target="#templateViewModel"
                    >
                        <i class="bi bi-eye-fill"></i>
                    </button>
                    <a class="tw-border-solid tw-border tw-border-rounded-2 tw-w-full tw-p-2 tw-rounded-lg tw-bg-green-400 hover:tw-bg-green-500" href="{% url 'email-template-create' %}?edit={{ template.id }}">
                        Edit
                    </a>
                   
                </div>
            </div>
        {% endfor %}

    </div>  
</div>
<script src="{% static "./js/email-product/email-templates.js" %}"></script>

{% endblock content %}

templates/html/email-product/templates/public-templates.html
{% extends './html/base.html' %}
{% load static %}

{% block content %}
<div class="tw-flex tw-flex-col tw-min-h-screen tw-p-3 tw-place-items-center tw-gap-4"> <!-- Changed tw-min-h-[100vh] to tw-min-h-screen -->
    <div class="tw-text-center tw-mt-4">
        <p class="tw-text-2xl tw-font-bold">Public Email templates</p>
    </div>
    <div class="tw-flex tw-w-full tw-flex-col tw-place-items-center">
        <form method="get" action="{% url "email-templates" %}" 
              class="tw-flex tw-min-w-[350px] md:tw-min-w-[500px] tw-max-w-2xl">
            <div class="input-group">
                <input type="hidden" name="public" value="True">
                <input type="text" name="search" maxlength="100" class="form-control" 
                        placeholder="search templates" 
                        value="{{ search_query }}" aria-describedby="button-addon1">
                <button class="btn btn-primary" type="submit">
                    <i class="bi bi-search"></i>
                </button>
            </div>
        </form>

        <div class="tw-flex tw-w-full tw-flex-col tw-place-items-center tw-mt-[3%] tw-gap-3">
            {% if templates %}
                <div class="tw-flex tw-flex-wrap tw-place-content-center tw-gap-3">
                    {% for x in templates %}
                        <div class="tw-flex tw-flex-col tw-border-solid 
                                    tw-border
                                    tw-text-left 
                                    tw-justify-items-center 
                                    tw-place-items-center 
                                    tw-w-[250px] tw-h-[250px] 
                                    tw-rounded-lg tw-shadow-xl tw-p-3
                                    tw-overflow-hidden">
                            <b>{{ x.name }}</b>
                            <p class="tw-h-[80px] tw-overflow-auto tw-mt-2"><b>Subject:</b> {{ x.subject }}</p>
                            <p>by: {{ x.user.name }}</p>
                            <div class="tw-flex tw-gap-1 tw-mt-auto tw-w-[80%] tw-text-center">
                                <button onclick="viewTemplate({{x.id}})" class="btn !tw-max-w-fit" 
                                    data-bs-placement="bottom" title="View template"
                                    data-bs-toggle="modal" data-bs-target="#templateViewModel"
                                >
                                    <i class="bi bi-eye-fill"></i>
                                </button>
                                <a class="tw-border-solid tw-border tw-rounded-lg tw-bg-green-400 hover:tw-bg-green-500 tw-w-full tw-p-2" href="{% url 'email-template-create' %}?edit={{ x.id }}"> 
                                    Edit
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% elif search_query %}
                <div class="tw-text-center">
                    <p class="tw-text-lg">Search not found :( Try again with some other keyword</p>
                </div>
            {% else %}
                <div class="tw-text-center">
                    <p class="tw-text-lg">No templates Yet :(</p> 
                </div>
            {% endif %}
        </div>

        <ul class="pagination justify-content-center flex-wrap mb-4 !tw-mt-[5%]">
            {% if templates.has_previous %}
                <li class="page-item"><a class="page-link" href="?public=True&page={{ templates.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
            {% endif %}
            {% for i in templates.paginator.page_range %}
                {% if templates.number == i %}
                    <li class="page-item active"><span class="page-link">{{ i }}</span></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?public=True&page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if templates.has_next %}
                <li class="page-item"><a class="page-link" href="?public=True&page={{ templates.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
            {% endif %}
        </ul>
        

    </div>

</div>
{% endblock content %}